---
kind: pipeline
name: build
type: docker

concurrency:
  limit: 1

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive

- name: hugo
  image: akester/hugo
  commands:
  - hugo build

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [10.0.254.50]
    user: grumpy
    key:
      from_secret: deploy_key
    port: 2222
    target: /home/web/html/
    source: public/*
    delete: true
    recursive: true
  when:
    branch:
      - master

- name: cache
  image: alpine
  when:
    branch:
      include:
        - master
    event:
      exclude:
        - pull_request

  environment:
    CF_API_KEY:
      from_secret: cf_api_key
    CF_EMAIL:
      from_secret: cf_email
    ZONE_ID:
      from_secret: zone_id

  commands:
    - apk add --update bash curl
    - bash purge.sh
