---
kind: pipeline
name: build
type: docker

concurrency:
  limit: 1

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive

- name: hugo
  image: plugins/hugo

  settings:
    validate: true
    extended: true
    url: https://grumpy.systems
    hugo_version: 0.136

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [10.10.0.23]
    user: grumpy.systems
    key:
      from_secret: deploy_key
    port: 2222
    target: /home/web/html/
    source: public/*
    delete: true
    recursive: true
  when:
    branch:
      - master