---
kind: pipeline
name: build
type: docker

concurrency:
  limit: 1

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive

- name: hugo
  image: debian/bullseye
  commands:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.136.2/hugo_0.136.2_linux-amd64.deb
  - dpkg -i /tmp/hugo.deb

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [10.10.0.23]
    user: grumpy.systems
    key:
      from_secret: deploy_key
    port: 2222
    target: /home/web/html/
    source: public/*
    delete: true
    recursive: true
  when:
    branch:
      - master