baseURL: "https://grumpy.systems/"
languageCode: "en"
defaultContentLanguage: "en"
title: "Grumpy"
theme: "gokarna"

permalinks:
  posts: /:year/:title/

taxonomies:
    category: categories
    tag: tags
    series: series

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20

markup:
  highlight:
    noClasses: false

params:
  avatarURL: '/grumpy.jpg'
  customHeadHTML: |
    <!-- Highlight -->
    <link rel="stylesheet" href="/vendor/highlight/styles/stackoverflow-dark.min.css">
    <link rel="stylesheet" href="/css/custom.css">
  customFooterHTML: |
    <!-- Highlight -->
    <script src="/vendor/highlight/highlight.min.js"></script>
    <script src="/vendor/highlight-numbers.min.js"></script>

    <script>
      hljs.highlightAll();
      hljs.initLineNumbersOnLoad();
    </script>
  dateFormat: "January 2, 2006"

  numberPostsOnHomePage: 5
  showPostsOnHomePage: recent

  showBackToTopButton: true
  togglePreviousAndNextButtons: true

  footer: Grumpy

  description: I make content about computers and build things.

  socialIcons:
    - name: tiktok
      url: https://www.tiktok.com/@grumpy.systems
    - name: github
      url: https://github.com/grumpy-systems
    - name: youtube
      url: https://www.youtube.com/channel/UCnQkxe-l11qWYkwyg_svUCw
    - name: reddit
      url: https://reddit.com/u/grumpy-systems
    - name: mastodon
      url: https://infosec.exchange/@grumpysystems
    - name: email
      url: mailto:grumpy.systems@gmail.com

  oldContentWarning: true
  oldContentDuration: 1095

minify:
  minifyOutput: true