baseURL: "https://grumpy.systems/"
languageCode: "en-us"
title: "Grumpy"
theme: "anatole"

permalinks:
  posts: /:year/:title/

taxonomies:
    category: categories
    tag: tags
    series: series

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20

params:
  title: "I'm Grumpy"
  author: "Grumpy"
  description: "I make content about computers and build things."
  profilePicture: "/grumpy.jpg"
  copyright: "{{ YEAR }} Grumpy"
  displayMode: "dark"
  contentRatio: 0.8
  doNotLoadAnimations: true
  readMore: true
  mainSections: ["post"]
  oldContentWarning: true
  oldContentDuration: 1095 # 3 years
  disableThemeSwitcher: true
  customCss: ["custom.css"]