baseURL: "https://grumpy.systems/"
languageCode: "en-us"
title: "Grumpy"
theme: "hugo-book"

taxonomies:
    category: categories
    tag: tags
    series: series

outputs:
    home:
        - HTML

params:
  BookSection: '/'
  BookSearch: false
